#' BSOL ICS Theme Palettes
#'
#' This function returns a palette generated by colorRampPalette from one of the
#' BSOL palettes
#'
#' @param palette The name of palette to use
#' @param reverse Optional: boolean value to reverse the palette
#' @param ... arguments to pass to colorRamp
#'
#' @return A colorRamp function
#' @export
#'
#' @examples
#' bsol_theme_pal("main")
#' # or, specify a palette
#' bsol_theme_pal("ics_orange")
#' # a reverse palette
#' bsol_theme_pal("main", TRUE)
bsol_theme_pal <- function(palette = c(
                        "main",
                        "alternative",
                        "ics_blue",
                        "ics_orange",
                        "ics_green",
                        "ics_purple",
                        "ics_navy"
                         ),
                         reverse = FALSE,
                         ...) {
  palette <- match.arg(palette)

  pal <- bsol_theme_cols(palette = palette)

  if (reverse) pal <- rev(pal)

  grDevices::colorRampPalette(pal, ...)
}
