#' BSOL ICS Theme Palettes
#'
#' This function returns a palette generated by colorRampPalette from one of the
#' Strategy Unit palettes
#'
#' @param palette The name of palette to use
#' @param reverse Optional: boolean value to reverse the palette
#' @param ... arguments to pass to colorRamp
#'
#' @return A colorRamp function
#' @export
#'
#' @examples
#' bsol_theme_pal()
#' # or, specify a paltte
#' bsol_theme_pal("oranges")
#' # a reverse palette
#' bsol_theme_pal("slates", TRUE)
bsol_theme_pal <- function(palette = c(
                        "main",
                        "alternative",
                        "ics_blue",
                        "ics_orange",
                        "ics_green",
                        "ics_purple",
                        "ics_navy"
                         ),
                         reverse = FALSE,
                         ...) {
  palette <- match.arg(palette)

  pal <- bsol_theme_cols(palette = palette)

  if (reverse) pal <- rev(pal)

  grDevices::colorRampPalette(pal, ...)
}
